# Generated by Django 4.0.7 on 2022-10-05 10:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('type_projects', models.CharField(choices=[('Волонтерский', 'Волонтерский'), ('Коммерческий', 'Коммерческий')], default='Волонтерский', max_length=30, verbose_name='Тип проекта')),
                ('status', models.CharField(choices=[('Только идея', 'Только идея'), ('В поиске команды', 'В поиске команды'), ('Проект завершен', 'Проект завершен'), ('Проект заморожен', 'Проект заморожен')], default='Только идея', max_length=20, verbose_name='Статус проекта')),
                ('author', models.CharField(max_length=100, verbose_name='Автор проекта')),
                ('team', models.CharField(max_length=100, null=True, verbose_name='Команда')),
                ('participants_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Кол-во людей в команде')),
                ('link', models.TextField(verbose_name='Ссылка на подробное описанние проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects_card',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='ID Телеграм')),
                ('sername', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('tg_login', models.CharField(max_length=100, null=True, verbose_name='Логин')),
                ('gender', models.CharField(max_length=100, verbose_name='Пол')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='Телефон')),
                ('birthday', models.DateTimeField(verbose_name='Дата рождения пользователя')),
                ('end_blocking', models.DateTimeField(default=datetime.datetime(1999, 1, 1, 0, 0), verbose_name='Дата Окончания блокировки')),
                ('direction_blocking', models.TextField(verbose_name='Причина блокировки')),
                ('scores', models.IntegerField(verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users_card',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('type_vacancy', models.CharField(choices=[('Практики для студента', 'Практики для студента'), ('Работа для получения опыта', 'Работа для получения опыта'), ('Полноценное трудоустройство', 'Полноценное трудоустройство'), ('Все типы', 'Все типы')], default='Практики для студента', max_length=30, verbose_name='Тип вакансии')),
                ('busyness', models.CharField(choices=[('Разовая занятость', 'Разовая занятость'), ('Частичная занятость', 'Частичная занятость'), ('Полная занятость', 'Полная занятость')], default='Разовая занятость', max_length=100, verbose_name='Занятность')),
                ('schedule', models.CharField(choices=[('Стандартное время', 'Стандартное время'), ('Гибкий график', 'Гибкий график')], default='Стандартное время', max_length=100, verbose_name='График работы')),
                ('address', models.CharField(max_length=100, verbose_name='Адресс вакансии')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancy_card',
                'ordering': ['id'],
            },
        ),
    ]
