# Generated by Django 4.0.7 on 2022-12-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIPY_ADMIN', '0002_deletemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type_vacancy',
            field=models.CharField(choices=[('Практика', 'Практика'), ('Стажировка', 'Стажировка'), ('Работа', 'Работа'), ('Все типы', 'Все типы')], default='Практика', max_length=30, verbose_name='Тип вакансии'),
        ),
    ]
