# Generated by Django 4.0.7 on 2022-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KIPY_ADMIN', '0003_vacancy_active_alter_vacancy_type_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
                ('practice_period', models.CharField(choices=[('Сентябрь — Январь', 'Сентябрь — Январь'), ('Февраль — Май', 'Февраль — Май'), ('Июнь — Август', 'Июнь — Август')], max_length=100, verbose_name='Период практики')),
                ('description', models.TextField(verbose_name='Описание')),
                ('separator', models.CharField(choices=[('Внутреняя', 'Внутреняя'), ('Партнера', 'Партнера')], default='Внутреняя', max_length=100, verbose_name='Тип вакансии')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='mail',
            field=models.CharField(max_length=100, null=True, verbose_name='Почта'),
        ),
    ]
